CREATE TABLE [dbo].[ItemPrice]
(
	[ItemPriceId] INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ITEMPRICEID PRIMARY KEY, 
	[ItemId] INT NOT NULL, 
	[PriceTypeId] INT NOT NULL, 
	[Amount] MONEY NOT NULL DEFAULT 0.00, 
	[CreateDate] DATETIME NOT NULL DEFAULT GetDate(), 
	[LastUpdate] DATETIME NOT NULL DEFAULT GetDate(),
	CONSTRAINT [FK_ItemPrice_Item] FOREIGN KEY ([ItemId]) REFERENCES [Item]([ItemId]),
	CONSTRAINT [FK_ItemPrice_PriceType] FOREIGN KEY ([PriceTypeId]) REFERENCES [LkpPriceType]([PriceTypeId])
)
